# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

[tool.commitizen]
# Parse commit messages according to conventional commits to decide the next version
# increment, major, minor or patch, and create the Version Control System (VCS)
# tag. Also supplies a VCS integration to enforce conventional commit messages:
# https://commitizen-tools.github.io/commitizen/
name = "cz_conventional_commits"
# TEMPLATE: Update these versions to the current version for your project and verify the
# tag exists locally and on the project's remote:
changelog_start_rev = "v0.0.0"
version = "1.0.1"
tag_format = "v$version"
annotated_tag = true
gpg_sign = true
bump_message = """\
build(release): Version $current_version → $new_version

[actions skip]
[ci release]
"""
