# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

default:
  image:
    name: "$CI_REGISTRY_IMAGE:build-host"
    entrypoint:
      - "docker-entrypoint.sh"
  services:
    - "docker:dind"
  before_script:
    - "chown -R $PUID:$PGID ./"
  # TODO: Debug stale venv issues and restore cache once fixed

variables:
  # Secrets from the GitLab CI/CD Variables UI:
  CODECOV_TOKEN: "$CODECOV_TOKEN"
  DOCKER_PASS: "$DOCKER_PASS"
  GPG_PASSPHRASE: "$GPG_PASSPHRASE"
  GPG_SIGNING_PRIVATE_KEY: "$GPG_SIGNING_PRIVATE_KEY"
  PYPI_PASSWORD: "$PYPI_PASSWORD"
  TEST_PYPI_PASSWORD: "$TEST_PYPI_PASSWORD"
  PROJECT_GITHUB_PAT: "$PROJECT_GITHUB_PAT"

  # Variables controlling behavior:
  PUID: "1001"
  PGID: "1001"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE"

  # Uncomment to get more debugging output:
  # DEBUG: "true"

stages:
  - "build-test"
  - "release"
  - "scheduled"

build-test:
  stage: "build-test"
  rules:
    - if: >-
        $CI_COMMIT_TAG
      when: "never"
    - if: >-
        (
          $CI_COMMIT_REF_PROTECTED != "true" || $CI_COMMIT_TITLE !~
          /^build\(release\): Version [0-9]\.[0-9]\.[0-9][a-z0-9-.]* → [0-9]\.[0-9]\.[0-9][a-z0-9-.]*$/
        )
        && $CI_PIPELINE_SOURCE != "schedule"
  parallel:
    matrix:
      - PYTHON_MINORS:
          - "3.11"
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
  script:
    # Delegate steps agnostic of the CI/CD platform to the `./Makefile`:
    - >-
      entrypoint make -e check-push
      build-docker-$PYTHON_MINORS
      test-docker-$PYTHON_MINORS
      release-docker-$PYTHON_MINORS check-clean
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    # Upload build artifacts:
    # https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html
    paths:
      - "./build/py*/pytest*"
      - "./build/py*/.coverage*"
      - "./build/py*/coverage*"
      - "./build/py*/htmlcov"
      - "./build/py*/prospector*"
      - "./build/py*/pylint*"
    reports:
      junit:
        - "./build/py*/pytest-junit.xml"
        - "./build/py*/prospector-xunit.xml"
      coverage_report:
        coverage_format: "cobertura"
        path: "./build/py*/coverage.xml"

release:
  stage: "release"
  needs: ["build-test"]
  # Avoid unnecessary artifact downloads:
  # https://docs.gitlab.com/ee/ci/yaml/#dependencies
  dependencies: []
  rules:
    - if: >-
        $CI_COMMIT_TAG
      when: "never"
    - if: >-
        $CI_COMMIT_REF_PROTECTED == "true"
        && $CI_PIPELINE_SOURCE != "schedule"
  script:
    - >-
      entrypoint make -e BUILD_REQUIREMENTS=false
      build-bump check-clean
      release-python check-clean
  artifacts:
    paths:
      - "./NEWS-release.rst"
      - "./dist/python?project?structure-*"

scheduled:
  stage: "scheduled"
  rules:
    - if: >-
        $CI_PIPELINE_SOURCE == "schedule"
  script:
    - >-
      entrypoint make -e $SCHEDULED_TARGETS
