# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

# Minimal `$ docker compose` configuration to show the requirements for running
# project-structure in containers.

services:
  ## Container for use by end users:
  project-structure:
    image: "merpatterson/project-structure"
    container_name: "project-structure"
    environment:
      # Match the time zone of the host through `./.env`:
      TZ: "${TZ:-Etc/UTC}"
      # Make the runtime user configurable in `./.env` to match permissions inside and
      # outside the container.  Default to the common/standard main/first user and group
      # IDs
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-${PUID:-1000}}"
      # Pass in from the environment or set to `true` here to get more verbose `DEBUG`
      # logging:
      DEBUG: "${DEBUG:-}"
    restart: "unless-stopped"
    volumes:
      # Preserve user configuration, data, and caches between containers and variants:
      - type: "volume"
        source: "home_config"
        target: "/home/project-structure/.config"
      - type: "volume"
        source: "home_local_share"
        target: "/home/project-structure/.local/share"
      - type: "volume"
        source: "home_cache"
        target: "/home/project-structure/.cache"
      # Preserve shell history inside containers, requires `$ touch
      # ./home/.bash_history`:
      - "./home/.bash_history:/home/project-structure/.bash_history"

volumes:
  # Share user `${HOME}` data between services but isolated within the project:
  home_config: &volume-bind
    name: "${PROJECT_NAME:-prunerr}_home_config"
    driver: "local"
    driver_opts: &volume-bind-opts
      type: "none"
      o: "bind"
      device: "${CHECKOUT_DIR:-.}/home/.config/"
  home_local_share:
    <<: *volume-bind
    name: "${PROJECT_NAME:-prunerr}_home_local_share"
    driver_opts:
      <<: *volume-bind-opts
      device: "${CHECKOUT_DIR:-.}/home/.local/share/"
  home_cache:
    <<: *volume-bind
    name: "${PROJECT_NAME:-prunerr}_home_cache"
    driver_opts:
      <<: *volume-bind-opts
      device: "${CHECKOUT_DIR:-.}/home/.cache/"
