# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

# Override `$ docker compose` configuration for development or testing here in this
# repository checkout. Put everything used outside this checkout in
# `./docker-compose.yml`.
version: "3.8"

services:
  # https://github.com/hadolint/hadolint#how-to-use
  hadolint:
    image: "ghcr.io/hadolint/hadolint"
    profiles:
      - "test"
    environment:
      TZ: "${TZ:-Etc/UTC}"
    volumes:
      - "${CHECKOUT_DIR:-.}/:${CHECKOUT_DIR:-/usr/local/src/project-structure}/"
    working_dir: >-
      ${CHECKOUT_DIR:-/usr/local/src/project-structure}${WORKING_DIR_SUFFIX:-}
    command: >-
      hadolint "./Dockerfile"

  reuse:
    image: "docker.io/fsfe/reuse:latest-debian"
    profiles:
      - "lint"
    user: "${PUID:-1000}:${PGID:-${PUID:-1000}}"
    environment:
      TZ: "${TZ:-Etc/UTC}"
    volumes:
      - "${CHECKOUT_DIR:-.}/:${CHECKOUT_DIR:-/usr/local/src/project-structure}/"
    working_dir: >-
      ${CHECKOUT_DIR:-/usr/local/src/project-structure}${WORKING_DIR_SUFFIX:-}
    command: >-
      lint

  vale:
    image: "docker.io/jdkato/vale"
    profiles:
      - "lint"
    user: "${PUID:-1000}:${PGID:-${PUID:-1000}}"
    environment:
      TZ: "${TZ:-Etc/UTC}"
    volumes:
      - "${CHECKOUT_DIR:-.}/:${CHECKOUT_DIR:-/usr/local/src/project-structure}"
    working_dir: >-
      ${CHECKOUT_DIR:-/usr/local/src/project-structure}${WORKING_DIR_SUFFIX:-}
    command: >-
      .

  ## Containers for simulating CI/CD:

  build-host:
    image: "${DOCKER_USER:-}/project-structure:build-host"
    profiles:
      - "ci"
    build:
      context: "./build-host/"
      args:
        BUILDKIT_INLINE_CACHE: "1"
        USER_SIGNINGKEY: "${USER_SIGNINGKEY:-}"
      cache_from:
        - "${DOCKER_USER:-}/project-structure:build-host"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CHECKOUT_DIR:-.}/:${CHECKOUT_DIR:-.}"
      - "${CHECKOUT_DIR:-.}${WORKING_DIR_SUFFIX:-}/build-host/bin/init-job.sh\
        :/usr/local/bin/init-job.sh"
      - "${CHECKOUT_DIR:-.}${WORKING_DIR_SUFFIX:-}/build-host/bin/entrypoint.sh\
        :/usr/local/bin/entrypoint.sh"
      # Share local authentication inside the container:
      - "~/.ssh/:/home/runner/.ssh/"
      - "${SSH_AUTH_SOCK:-/run/user/${PUID:-1000}/ssh/agent.socket}\
        :${SSH_AUTH_SOCK:-/run/user/${PUID:-1000}/ssh/agent.socket}"
      - "~/.gnupg/:/home/runner/.gnupg/"
      - "/run/user/${PUID:-1000}/gnupg/S.gpg-agent:/home/runner/.gnupg/S.gpg-agent"
    env_file: "./.env"
    environment:
      TZ: "${TZ:-Etc/UTC}"
      PUID: "${PUID:-1000}"
      PGID: "${DOCKER_GID:-${PGID:-${PUID:-1000}}}"
      SSH_AUTH_SOCK: "${SSH_AUTH_SOCK:-/run/user/${PUID:-1000}/ssh/agent.socket}"
      # DEBUG: "true"
    working_dir: "${CHECKOUT_DIR:-.}${WORKING_DIR_SUFFIX:-}"
    command: >-
      make -O -j -e release-all
