# SPDX-FileCopyrightText: 2023 Ross Patterson <me@rpatterson.net>
#
# SPDX-License-Identifier: MIT

[tox]
env_list =
# TODO: Audit what checks all tools perform and remove redundant tools.
    build-docs-{rstcheck,sphinx-lint,doc8,sphinx,proselint}
isolated_build = True


# Virtual environments for tools that aren't a part of testing project code such as
# build, test, lint, and release tools. To optimize Tox's parallel execution and
# minimize interaction issues, use separate venvs for each tool independently wherever
# possible:

[testenv:build-pip-tools]
description = Independent build and release tools
skip_install = true
# Run these tools against the best Python version available on the host which should be
# the same version that the `./Makefile` exports in `${PYTHON_HOST_ENV}` and is used in
# `deps = ` below:
base_python =
    python3.12
    python3.11
    python3.10
    python3.9
    python3.8
# If the officially supported Python version is available on the host, then this
# contains the compiled pinned versions for reproducible results. Otherwise use the best
# Python version available on the host and this is a symbolic link to the base,
# uncompiled requirements without pinned versions:
deps = -r .{/}requirements{/}{env:PYTHON_HOST_ENV:py312}{/}{envname}.txt
commands =
    pip-compile --strip-extras --generate-hashes --reuse-hashes --allow-unsafe --quiet \
        {env:pip_compile_args} \
        --output-file ".{/}requirements{/}{env:PYTHON_HOST_ENV:py312}{/}{env:requirements_stem}.txt" \
	"./requirements{/}{env:requirements_stem}.txt.in"
# Tox's CLI option for overriding configurtation only works for keys that Tox itself
# uses, not the arbitrary "variable" keys that can be used in substitutions. IOW `-x
# testenv:py312.deps=foo-package` works but `-x testenv:py312.bar_variable=foo-package`
# does not. So the only option to abstract the values we need to construct the final
# configuration that can also be overridden on the CLI is to abuse/overload `set_env`:
set_env =
    pip_compile_args=
    requirements_stem={envname}
[testenv:lint]
description = Independent linters
base = testenv:build-pip-tools
allowlist_externals =
# Apply the tool to the right subset of files when it doesn't support that through
# configuration:
    git
    xargs
[testenv:lint-rstcheck]
description = Check the syntax of reStructuredText and nested code blocks
deps =
    -r ./requirements{/}{env:PYTHON_HOST_ENV:py312}{/}lint{/}rstcheck.txt
commands =
# Verify reStructuredText syntax. Exclude `./docs/index.rst` because its use of the
# `.. include:: ../README.rst` directive breaks `$ rstcheck`:
#     CRITICAL:rstcheck_core.checker:An `AttributeError` error occured.
# Also exclude `./docs/news*.rst` because it's duplicate headings cause:
#     INFO docs/news.rst:317 Duplicate implicit target name: "bugfixes".
    git ls-files -z '*.rst' ':!docs/index.rst' ':!docs/news*.rst' |
        xargs -r -0 -- rstcheck
[testenv:lint-sphinx-lint]
deps =
    -r ./requirements{/}{env:PYTHON_HOST_ENV:py312}{/}lint{/}sphinx-lint.txt
commands =
[testenv:lint-doc8]
deps =
    -r ./requirements{/}{env:PYTHON_HOST_ENV:py312}{/}lint{/}doc8.txt
commands =
[testenv:lint-sphinx]
deps =
    -r ./requirements{/}{env:PYTHON_HOST_ENV:py312}{/}lint{/}sphinx.txt
commands =
[testenv:lint-{sphinx-lint,doc8,sphinx,proselint}]
deps =
    
commands =

[doc8]
max-line-length=88
